#!/bin/bash

# modify the env vars below to change where the bins are 
# for the i386 toolchain

# Usage: source build; build

I386_GCC_BIN_PATH="$HOME/resources/i386-elf-gcc/bin/"
I386_AS_BIN_PATH="$HOME/resources/i386-elf-binutils/bin/"
I386_AS_ABSOLUTE_PATH="$HOME/resources/i386-elf-binutils/bin/i386-elf-as"
TEMP_DIR_NAME="temp"

build () {
    mkdir "$TEMP_DIR_NAME"
    ! cd "$TEMP_DIR_NAME" && rmdir "$TEMP_DIR_NAME" && exit 1
    cp "$I386_AS_ABSOLUTE_PATH" "$PWD"
    ln -sf "./$(basename "$I386_AS_ABSOLUTE_PATH")" "as"
    cd ..
    export PATH="${I386_GCC_BIN_PATH}:${PATH}"
    export PATH="${I386_AS_BIN_PATH}:${PATH}"
    export PATH="${PWD}/${TEMP_DIR_NAME}:${PATH}"

    PATH="${I386_GCC_BIN_PATH}:${PATH}" make TOOLPREFIX=i386-elf- qemu-nox

    rm -rf $TEMP_DIR_NAME
}
