#!/bin/bash
# This should be ran in the same directory the script is located at!
# Also assumes qemu and git are installed. Should be noted for Ubuntu QEMU package
# that 'qemu' is a dummy package, various architectures are supported through the package
# 'qemu-system'.

XV6_DIRECTORY_NAME="xv6-public"
PROGRAM_NAME="setup_project"

# clone xv6 public repo
git clone https://github.com/mit-pdos/xv6-public "$XV6_DIRECTORY_NAME"

# move contents to ../src directory, 
cd "$XV6_DIRECTORY_NAME" || exit 1

# sloppy, may replace later (see SC2207 for shellcheck's opinion!)
# shellcheck disable=SC2207
SRC_FILES=($(ls --almost-all))
for fil in "${SRC_FILES[@]}"; do mv --no-clobber "$fil" "../"; done || exit 1;
cd .. || exit 1
rmdir "$XV6_DIRECTORY_NAME"

# some resources needed can be checked from path sets in some env vars
# shellcheck disable=SC1091
source build

# making sure the cross compiler and assembler parent directories exist
# as build only attaches the respective bin directory paths to PATH
if ! [ -d "$(dirname GCC_BIN_PATH)" ] || ! [ -d "$(dirname AS_BIN_PATH)" ]; then
    echo "${PROGRAM_NAME}: download the i386 gcc/binutils packages and attach their bin locations to/from the build.sh"
    exit 1
fi

make mkfs
build
