#!/bin/bash
#
# This script is used to setup the initial-xv6 project for ostep.
# NOTE: This should be ran in the same directory the script is located at!

XV6_URL="https://github.com/mit-pdos/xv6-public"
XV6_DIRECTORY_NAME="$(basename "$XV6_URL")"
PROGRAM_NAME="$(basename "$0")"

if [ -d "$XV6_DIRECTORY_NAME" ]; then
    rm --recursive --force "$XV6_DIRECTORY_NAME"
fi

# clone xv6 public repo
git clone "$XV6_URL" "$XV6_DIRECTORY_NAME"

# move contents to ../src directory, 
cd "$XV6_DIRECTORY_NAME" || exit 1

for f in ./*; do
    # removing the $PWD notation './' from the file name
    f="${f:2:${#f}}"
    if [ "$f" != ".git" ] && [ "$f" != "$XV6_DIRECTORY_NAME" ]; then 
        mv --no-clobber "$f" "../"; 
    fi; 
done || exit 1;

cd .. || exit 1
rm --recursive --force "$XV6_DIRECTORY_NAME"
