#!/bin/bash
# This should be ran in the same directory the script is located at!

XV6_DIRECTORY_NAME="xv6-public"
PROGRAM_NAME="setup_project"

# clone xv6 public repo
git clone https://github.com/mit-pdos/xv6-public "$XV6_DIRECTORY_NAME"

# move contents to ../src directory, 
cd "$XV6_DIRECTORY_NAME" || exit 1

# sloppy, may replace later (see SC2207 for shellcheck's opinion!)
# shellcheck disable=SC2207
SRC_FILES=($(ls --almost-all))
for fil in "${SRC_FILES[@]}"; do if [ "$fil" != ".git" ]; then mv --no-clobber "$fil" "../"; fi; done || exit 1;
cd .. || exit 1
rm -rf "$XV6_DIRECTORY_NAME"
